<?php
/**
 * @author      Olegnax
 * @package     Olegnax_GoogleMap
 * @copyright   Copyright (c) 2020 Olegnax (http://olegnax.com/). All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Olegnax\GoogleMap\Model\Location;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var array $icon */
/** @var Location $location */

$viewBox = '0 0 ' . implode(' ', $icon['scaledSize']);
$markerScale = $location->getMarkerSize();
?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
	 viewBox="<?= $viewBox ?>" xml:space="preserve">
<circle cx="18" cy="18" r="18" fill="<?= $location->getMarkerColor1() ?>" transform="scale(<?= $markerScale ?>)"/>
	<circle cx="18" cy="18" r="4" fill="<?= $location->getMarkerColor2() ?>" transform="scale(<?= $markerScale ?>)"/>
</svg>
