<?php
/**
 * @author      Olegnax
 * @package     Olegnax_GoogleMap
 * @copyright   Copyright (c) 2020 Olegnax (http://olegnax.com/). All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Olegnax\GoogleMap\Model\Location;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var array $icon */
/** @var Location $location */

$viewBox = '0 0 ' . implode(' ', $icon['scaledSize']);
$markerScale = $location->getMarkerSize();
?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"	viewBox="<?= $viewBox ?>" xml:space="preserve">
<ellipse class="ox-marker-shadow" cx="17.5" cy="33.2" rx="12.1" ry="1.8" fill="<?= $location->getMarkerShadowColor() ?>" transform="scale(<?= $markerScale ?>)"/>
<path d="M11,34L11,34c-1.1,0-2-0.9-2-2V2c0-1.1,0.9-2,2-2h0c1.1,0,2,0.9,2,2v30C13,33.1,12.1,34,11,34z" fill="<?= $location->getMarkerColor1() ?>" transform="scale(<?= $markerScale ?>)"/>
<polygon points="9,0 35,0 28,8 35,16 9,16 " fill="<?= $location->getMarkerColor2() ?>" transform="scale(<?= $markerScale ?>)"/>
</svg>