<?php
/**
 * @author      Olegnax
 * @package     Olegnax_GoogleMap
 * @copyright   Copyright (c) 2020 Olegnax (http://olegnax.com/). All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Olegnax\GoogleMap\Model\Location;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var array $icon */
/** @var Location $location */

$viewBox = '0 0 ' . implode(' ', $icon['scaledSize']);
$markerScale = $location->getMarkerSize();
?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="<?= $viewBox ?>" xml:space="preserve">
    <ellipse class="ox-marker-shadow" cx="17" cy="39.5" rx="11" ry="1.5" fill="<?= $location->getMarkerShadowColor() ?>"
			 transform="scale(<?= $markerScale ?>)"/>
	<path d="M29.6,28.4L18.7,39.3c-0.9,0.9-2.5,0.9-3.4,0L4.4,28.4" fill="<?= $location->getMarkerColor1() ?>"
		  transform="scale(<?= $markerScale ?>)"/>
	<path d="M17,0C7.6,0,0,7.6,0,17s7.6,17,17,17s17-7.6,17-17S26.4,0,17,0z M17,24.2c-3.9,0-7-3.1-7-7s3.1-7,7-7s7,3.1,7,7
			S20.9,24.2,17,24.2z" fill="<?= $location->getMarkerColor1() ?>" transform="scale(<?= $markerScale ?>)"/>
</svg>
