<?php
/**
 * @author      Olegnax
 * @package     Olegnax_GoogleMap
 * @copyright   Copyright (c) 2020 Olegnax (http://olegnax.com/). All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Olegnax\GoogleMap\Model\Data\Location as DataLocation;
use Olegnax\GoogleMap\Model\Location;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var array $icon */
/** @var Location $location */

$viewBox = '0 0 ' . implode(' ', $icon['scaledSize']);
$markerScale = $location->getMarkerSize();
$markerSize = 70;
$innerScale = 0.7;
$imageScaled = $markerSize * $innerScale * $markerScale;
$innerPosition = (($markerSize-($markerSize*$innerScale))/2);
$image = $block->getData('widgetBlock')->contentLocalImage(DataLocation::MARKER_IMAGE, $location);
?>
<svg preserveaspectratio="xMidYMid meet" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="<?= $viewBox ?>">
	<ellipse class="ox-marker-shadow" cx="<?= (($markerSize/2) - 6) ?>" cy="<?= ($markerSize - 4) ?>" rx="12" ry="2" fill="<?= $location->getMarkerShadowColor() ?>" transform="scale(<?= $markerScale ?>)"/>
	<rect width="<?= $markerSize ?>" height="<?= $markerSize ?>" fill="<?= $location->getMarkerColor1() ?>" transform="scale(<?= $markerScale ?>)"/>
	<rect x="<?= $innerPosition ?>" y="<?= $innerPosition ?>" width="<?= $markerSize*$innerScale ?>" height="<?= $markerSize*$innerScale ?>" fill="<?= $location->getMarkerColor2() ?>" transform="scale(<?= $markerScale ?>)"/>
	<polygon points="36.3,78.5 27.8,70 36.3,70 44.8,70 " fill="<?= $location->getMarkerColor1() ?>" transform="scale(<?= $markerScale ?>)"/>
	 <?php if ($image): ?>
		<defs>
			<clipPath id="oxImageMask">
				<rect x="<?= $innerPosition ?>" y="<?= $innerPosition ?>" width="<?= $markerSize*$innerScale ?>" height="<?= $markerSize*$innerScale ?>" fill="<?= $location->getMarkerColor2() ?>" transform="scale(<?= $markerScale ?>)"/>        
			</clipPath>
		</defs>
		<image width="<?= $imageScaled ?>" height="<?= $imageScaled ?>" x="<?= $innerPosition*$markerScale ?>" y="<?= $innerPosition*$markerScale ?>" xlink:href="<?= $image ?>" clip-path="url(#oxImageMask)" />
	<?php endif; ?>
</svg>